Repository rubyists/leopard, pull requests merged in 2025-08, with the labels that each got.

#18 feat: Adds graceful shutdown when INT/TERM/QUIT signal is received
  Gemfile.lock
  examples/echo_endpoint.rb
  lib/leopard/nats_api_server.rb
  test/lib/nats_api_server.rb
Labels: enhancement

#19 chore(main): release 0.1.6
  .release-please-manifest.json
  .version.txt
  CHANGELOG.md
  lib/leopard/version.rb
Labels: autorelease: pending

#23 fix: Stop sending code argument to respond_with_error, it does not accept it
  Gemfile.lock
  examples/echo_endpoint.rb
  lib/leopard/message_wrapper.rb
  test/lib/message_wrapper.rb
Labels: bug

#27 fix: Allow non blocking all the way down to the instance level
  lib/leopard/nats_api_server.rb
Labels: enhancement

#26 chore(main): release 0.1.7
  .release-please-manifest.json
  .version.txt
  CHANGELOG.md
  lib/leopard/version.rb
Labels: autorelease: pending

#31 chore(main): release 0.2.1
  .release-please-manifest.json
  .version.txt
  CHANGELOG.md
  lib/leopard/version.rb
Labels: autorelease: pending
